# Generated by Django 5.0.7 on 2024-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Class', models.IntegerField()),
                ('Department', models.CharField(max_length=30)),
            ],
        ),
    ]
