# Generated by Django 5.0.7 on 2024-07-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Department',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Class',
            new_name='standard',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='StudentNumber',
            new_name='studentNumber',
        ),
    ]
