# Generated by Django 5.0.7 on 2024-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_studentgrades_alter_studentmarks_studentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='grade',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='studentNumber',
            field=models.IntegerField(),
        ),
    ]
