# Generated by Django 5.0.7 on 2024-07-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_alter_studentgrades_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='standard',
            new_name='Class',
        ),
    ]
