# Generated by Django 5.0.7 on 2024-07-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_rename_standard_studentdetails_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Class',
            new_name='standard',
        ),
    ]
